export const normalizeAction = (value) => {
  const action = String(value || '').trim().toLowerCase();
  return ['dashboard', 'requeue', 'run_now', 'incident_update', 'runbook_preview', 'runbook_execute', 'post_incident_update', 'prevention_action_update', 'postmortem_update', 'change_register', 'change_approve', 'change_start', 'change_complete'].includes(action) ? action : 'dashboard';
};

export const normalizeLimit = (value, fallback, min, max) => {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.max(min, Math.min(max, Math.round(number)));
};

export const normalizeNote = (value, max = 500) => String(value || '')
  .replace(/\s+/g, ' ')
  .trim()
  .slice(0, max);

export const normalizeOperationsError = (error) => {
  const source = [error?.code, error?.message, error?.details, error?.hint]
    .map((item) => String(item || ''))
    .join(' ')
    .toUpperCase();

  const known = [
    'DOKE_ORDER_OPS_AUTH_REQUIRED',
    'DOKE_ORDER_OPS_ROLE_REQUIRED',
    'DOKE_ORDER_EVENT_KEY_REQUIRED',
    'DOKE_ORDER_EVENT_REQUEUE_NOTE_REQUIRED',
    'DOKE_ORDER_EVENT_NOT_FOUND',
    'DOKE_ORDER_EVENT_REQUEUE_NOT_ALLOWED',
    'DOKE_ORDER_EVENT_ATTEMPT_LIMIT_REACHED',
    'DOKE_ORDER_INCIDENT_ID_REQUIRED',
    'DOKE_ORDER_INCIDENT_ACTION_INVALID',
    'DOKE_ORDER_INCIDENT_NOTE_REQUIRED',
    'DOKE_ORDER_INCIDENT_NOT_FOUND',
    'DOKE_ORDER_INCIDENT_CLOSED',
    'DOKE_ORDER_INCIDENT_ALREADY_OWNED',
    'DOKE_ORDER_INCIDENT_ASSIGN_ADMIN_REQUIRED',
    'DOKE_ORDER_INCIDENT_ASSIGNEE_REQUIRED',
    'DOKE_ORDER_INCIDENT_ASSIGNEE_INVALID',
    'DOKE_ORDER_RUNBOOK_ALERT_REQUIRED',
    'DOKE_ORDER_RUNBOOK_ALERT_NOT_FOUND',
    'DOKE_ORDER_RUNBOOK_ALERT_CLOSED',
    'DOKE_ORDER_RUNBOOK_NOT_AVAILABLE',
    'DOKE_ORDER_RUNBOOK_PREVIEW_NOT_FOUND',
    'DOKE_ORDER_RUNBOOK_PREVIEW_EXPIRED',
    'DOKE_ORDER_RUNBOOK_PREVIEW_USED',
    'DOKE_ORDER_RUNBOOK_TOKEN_INVALID',
    'DOKE_ORDER_RUNBOOK_ADMIN_REQUIRED',
    'DOKE_ORDER_RUNBOOK_CONFIRMATION_INVALID',
    'DOKE_ORDER_RUNBOOK_NOTE_REQUIRED',
    'DOKE_ORDER_RUNBOOK_PREVIEW_STALE',
    'DOKE_ORDER_RUNBOOK_EVENT_REQUIRED',
    'DOKE_ORDER_RUNBOOK_EVENT_INVALID',
    'DOKE_ORDER_RUNBOOK_EXECUTION_FAILED',
    'DOKE_ORDER_POST_INCIDENT_REVIEW_REQUIRED',
    'DOKE_ORDER_POST_INCIDENT_ACTION_INVALID',
    'DOKE_ORDER_POST_INCIDENT_CATEGORY_INVALID',
    'DOKE_ORDER_POST_INCIDENT_FACTORS_INVALID',
    'DOKE_ORDER_POST_INCIDENT_NOT_FOUND',
    'DOKE_ORDER_POST_INCIDENT_ADMIN_REQUIRED',
    'DOKE_ORDER_POST_INCIDENT_ALREADY_DRAFT',
    'DOKE_ORDER_POST_INCIDENT_COMPLETED',
    'DOKE_ORDER_POST_INCIDENT_COMPLETION_INCOMPLETE',
    'DOKE_ORDER_PREVENTION_ACTION_INVALID',
    'DOKE_ORDER_PREVENTION_TITLE_REQUIRED',
    'DOKE_ORDER_PREVENTION_DUE_REQUIRED',
    'DOKE_ORDER_PREVENTION_OWNER_INVALID',
    'DOKE_ORDER_PREVENTION_ASSIGN_ADMIN_REQUIRED',
    'DOKE_ORDER_PREVENTION_ACTION_REQUIRED',
    'DOKE_ORDER_PREVENTION_NOT_FOUND',
    'DOKE_ORDER_PREVENTION_OWNER_REQUIRED',
    'DOKE_ORDER_PREVENTION_ADMIN_REQUIRED',
    'DOKE_ORDER_POSTMORTEM_ID_REQUIRED',
    'DOKE_ORDER_POSTMORTEM_CATEGORY_INVALID',
    'DOKE_ORDER_POSTMORTEM_FIELDS_REQUIRED',
    'DOKE_ORDER_POSTMORTEM_COMPLETE_ADMIN_REQUIRED',
    'DOKE_ORDER_POSTMORTEM_NOT_FOUND',
    'DOKE_ORDER_CHANGE_ID_REQUIRED',
    'DOKE_ORDER_CHANGE_NOT_FOUND',
    'DOKE_ORDER_CHANGE_KEY_INVALID',
    'DOKE_ORDER_CHANGE_TYPE_INVALID',
    'DOKE_ORDER_CHANGE_RISK_INVALID',
    'DOKE_ORDER_CHANGE_TITLE_REQUIRED',
    'DOKE_ORDER_CHANGE_KEY_FINALIZED',
    'DOKE_ORDER_CHANGE_OVERRIDE_ADMIN_REQUIRED',
    'DOKE_ORDER_CHANGE_OVERRIDE_REASON_REQUIRED',
    'DOKE_ORDER_CHANGE_HARD_BLOCKED',
    'DOKE_ORDER_CHANGE_OVERRIDE_NOT_REQUIRED',
    'DOKE_ORDER_CHANGE_APPROVAL_REQUIRED',
    'DOKE_ORDER_CHANGE_BLOCKED',
    'DOKE_ORDER_CHANGE_CONFIRMATION_INVALID',
    'DOKE_ORDER_CHANGE_OUTCOME_INVALID',
    'DOKE_ORDER_CHANGE_COMPLETION_NOTE_REQUIRED',
    'DOKE_ORDER_CHANGE_NOT_STARTED',
    'DOKE_ORDER_CHANGE_FINALIZED',
    'DOKE_ORDER_CHANGE_DECISION_IMMUTABLE',
  ].find((code) => source.includes(code));

  return known || 'DOKE_ORDER_OPS_FAILED';
};

export const statusForError = (code) => {
  if (code === 'DOKE_ORDER_OPS_AUTH_REQUIRED') return 401;
  if (code === 'DOKE_ORDER_OPS_ROLE_REQUIRED') return 403;
  if (code === 'DOKE_ORDER_EVENT_NOT_FOUND' || code === 'DOKE_ORDER_INCIDENT_NOT_FOUND' || code === 'DOKE_ORDER_RUNBOOK_ALERT_NOT_FOUND' || code === 'DOKE_ORDER_RUNBOOK_PREVIEW_NOT_FOUND' || code === 'DOKE_ORDER_POST_INCIDENT_NOT_FOUND' || code === 'DOKE_ORDER_PREVENTION_NOT_FOUND' || code === 'DOKE_ORDER_POSTMORTEM_NOT_FOUND' || code === 'DOKE_ORDER_CHANGE_NOT_FOUND') return 404;
  if (code === 'DOKE_ORDER_POST_INCIDENT_COMPLETED' || code === 'DOKE_ORDER_POST_INCIDENT_ALREADY_DRAFT' || code === 'DOKE_ORDER_CHANGE_KEY_FINALIZED' || code === 'DOKE_ORDER_CHANGE_HARD_BLOCKED' || code === 'DOKE_ORDER_CHANGE_OVERRIDE_NOT_REQUIRED' || code === 'DOKE_ORDER_CHANGE_APPROVAL_REQUIRED' || code === 'DOKE_ORDER_CHANGE_BLOCKED' || code === 'DOKE_ORDER_CHANGE_NOT_STARTED' || code === 'DOKE_ORDER_CHANGE_FINALIZED') return 409;
  if (code === 'DOKE_ORDER_EVENT_REQUEUE_NOT_ALLOWED' || code === 'DOKE_ORDER_EVENT_ATTEMPT_LIMIT_REACHED' || code === 'DOKE_ORDER_INCIDENT_CLOSED' || code === 'DOKE_ORDER_INCIDENT_ALREADY_OWNED' || code === 'DOKE_ORDER_RUNBOOK_ALERT_CLOSED' || code === 'DOKE_ORDER_RUNBOOK_NOT_AVAILABLE' || code === 'DOKE_ORDER_RUNBOOK_PREVIEW_EXPIRED' || code === 'DOKE_ORDER_RUNBOOK_PREVIEW_USED' || code === 'DOKE_ORDER_RUNBOOK_PREVIEW_STALE') return 409;
  if (code === 'DOKE_ORDER_INCIDENT_ASSIGN_ADMIN_REQUIRED' || code === 'DOKE_ORDER_RUNBOOK_TOKEN_INVALID' || code === 'DOKE_ORDER_RUNBOOK_ADMIN_REQUIRED' || code === 'DOKE_ORDER_POST_INCIDENT_ADMIN_REQUIRED' || code === 'DOKE_ORDER_PREVENTION_ASSIGN_ADMIN_REQUIRED' || code === 'DOKE_ORDER_PREVENTION_OWNER_REQUIRED' || code === 'DOKE_ORDER_PREVENTION_ADMIN_REQUIRED' || code === 'DOKE_ORDER_POSTMORTEM_COMPLETE_ADMIN_REQUIRED' || code === 'DOKE_ORDER_CHANGE_OVERRIDE_ADMIN_REQUIRED') return 403;
  if (code === 'DOKE_ORDER_EVENT_KEY_REQUIRED' || code === 'DOKE_ORDER_EVENT_REQUEUE_NOTE_REQUIRED' || code === 'DOKE_ORDER_INCIDENT_ID_REQUIRED' || code === 'DOKE_ORDER_INCIDENT_ACTION_INVALID' || code === 'DOKE_ORDER_INCIDENT_NOTE_REQUIRED' || code === 'DOKE_ORDER_INCIDENT_ASSIGNEE_REQUIRED' || code === 'DOKE_ORDER_INCIDENT_ASSIGNEE_INVALID' || code === 'DOKE_ORDER_RUNBOOK_ALERT_REQUIRED' || code === 'DOKE_ORDER_RUNBOOK_CONFIRMATION_INVALID' || code === 'DOKE_ORDER_RUNBOOK_NOTE_REQUIRED' || code === 'DOKE_ORDER_RUNBOOK_EVENT_REQUIRED' || code === 'DOKE_ORDER_RUNBOOK_EVENT_INVALID' || code === 'DOKE_ORDER_POST_INCIDENT_REVIEW_REQUIRED' || code === 'DOKE_ORDER_POST_INCIDENT_ACTION_INVALID' || code === 'DOKE_ORDER_POST_INCIDENT_CATEGORY_INVALID' || code === 'DOKE_ORDER_POST_INCIDENT_FACTORS_INVALID' || code === 'DOKE_ORDER_POST_INCIDENT_COMPLETION_INCOMPLETE' || code === 'DOKE_ORDER_PREVENTION_ACTION_INVALID' || code === 'DOKE_ORDER_PREVENTION_TITLE_REQUIRED' || code === 'DOKE_ORDER_PREVENTION_DUE_REQUIRED' || code === 'DOKE_ORDER_PREVENTION_OWNER_INVALID' || code === 'DOKE_ORDER_PREVENTION_ACTION_REQUIRED' || code === 'DOKE_ORDER_POSTMORTEM_ID_REQUIRED' || code === 'DOKE_ORDER_POSTMORTEM_CATEGORY_INVALID' || code === 'DOKE_ORDER_POSTMORTEM_FIELDS_REQUIRED' || code === 'DOKE_ORDER_CHANGE_ID_REQUIRED' || code === 'DOKE_ORDER_CHANGE_KEY_INVALID' || code === 'DOKE_ORDER_CHANGE_TYPE_INVALID' || code === 'DOKE_ORDER_CHANGE_RISK_INVALID' || code === 'DOKE_ORDER_CHANGE_TITLE_REQUIRED' || code === 'DOKE_ORDER_CHANGE_OVERRIDE_REASON_REQUIRED' || code === 'DOKE_ORDER_CHANGE_CONFIRMATION_INVALID' || code === 'DOKE_ORDER_CHANGE_OUTCOME_INVALID' || code === 'DOKE_ORDER_CHANGE_COMPLETION_NOTE_REQUIRED') return 400;
  return 500;
};
